models/Patient.php
<?php
namespace app\models;
use Yii;

class Patient extends \yii\db\ActiveRecord
{
    public $photofile;

    public static function tableName()
    {
        return 'patient';
    }

    public function rules()
    {
        return [
            [['created_date', 'modified_date', 'birth_date'], 'safe'],
            [['name'], 'required'],
            [['age'], 'integer'],
            [['sex'], 'safe'],
            [['photofile'], 'file'],
            // [['file'], 'file'],
            [['name', 'photo', 'birth_place', 'status', 'scholarity', 'work_area', 'profession', 'experience', 'address', 'city', 'postal_code', 'phone', 'on_emergency', 'emergency_phone'], 'string', 'max' => 255],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_date' => 'Creado',
            'modified_date' => 'Modificado',
            'name' => 'Nombre',
            'sex' => 'Género',
            'birth_date' => 'Fecha de Nacimiento',
            'birth_place' => 'Lugar de Nacimiento',
            'age' => 'Edad',
            'status' => 'Edo. Civil',
            'scholarity' => 'Escolaridad',
            'work_area' => 'Área de Trabajo',
            'profession' => 'Puesto',
            'experience' => 'Antiguedad',
            'address' => 'Dirección',
            'city' => 'Municipio',
            'postal_code' => 'C.P.',
            'phone' => 'Teléfono',
            'on_emergency' => 'En Emergencia Acudir A',
            'emergency_phone' => 'Teléfono de Emergencia',
            'photofile' => 'Fotografía',
        ];
    }

    public function getParental()
    {
        return $this->hasMany(Parental::className(), ['patient_id' => 'id']);
    }

    public function getPersonal()
    {
        return $this->hasMany(Personal::className(), ['patient_id' => 'id']);
    }

    public function getPersonalHistory()
    {
        return $this->hasMany(PersonalHistory::className(), ['patient_id' => 'id']);
    }

    public function getQuirurgicalIntervention()
    {
        return $this->hasMany(QuirurgicalIntervention::className(), ['patient_id' => 'id']);
    }

    public function getHospitalization()
    {
        return $this->hasMany(Hospitalization::className(), ['patient_id' => 'id']);
    }

    public function getGynecoObstetric()
    {
        return $this->hasMany(GynecoObstetric::className(), ['patient_id' => 'id']);
    }

    public function getDiet()
    {
        return $this->hasMany(Diet::className(), ['patient_id' => 'id']);
    }
    public function getAddiction()
    {
        return $this->hasMany(Addiction::className(), ['patient_id' => 'id']);
    }
    public function getSystem()
    {
        return $this->hasMany(System::className(), ['patient_id' => 'id']);
    }
    public function getPhysical()
    {
        return $this->hasMany(Physical::className(), ['patient_id' => 'id']);
    }
    public function getLabtest()
    {
        return $this->hasMany(Labtest::className(), ['patient_id' => 'id']);
    }
    public function getAllergic()
    {
        return $this->hasMany(Allergic::className(), ['patient_id' => 'id']);
    }
}

controllers/PatientController.php
<?php
namespace app\controllers;

use app\models\Parental;
use app\models\Personal;
use app\models\Diet;
use app\models\Addiction;
use app\models\System;
use app\models\Physical;
use app\models\Labtest;
use app\models\Allergic;
use app\models\PersonalHistory;
use app\models\QuirurgicalIntervention;
use app\models\Hospitalization;
use app\models\GynecoObstetric;
use app\models\form\PatientForm;
use Yii;
use app\models\Patient;
use app\models\PatientSearch;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;
use app\models\FormUpload;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;

class PatientController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionUpload($id)
    {
        $modelid = $this->findModel($id);
        $model = new FormUpload;
        $msg = null;

        $path = 'patients/'.$modelid->id.'/';
        FileHelper::createDirectory($path);

        if ($model->load(Yii::$app->request->post())) {
            $model->file = UploadedFile::getInstances($model, 'file');

            if ($model->file && $model->validate()) {
                foreach ($model->file as $file) {
                    $file->saveAs($path . $file->baseName . '.' . $file->extension);
                    $msg = "<p><strong class='label label-info'>Subida realizada</strong></p>";
                }
            }
        }
        return $this->render("upload", ["model" => $model, "msg" => $msg]);
    }

    public function actionIndex()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionReport()
    {
        $searchModel = new PatientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('report', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionAllergy($id)
    {
        $model = $this->findModel($id);



        return $this->render('view', [
            'model' => $model,
          ]);
    }


    public function actionView($id)
    {
        $model = $this->findModel($id);
        $modelDetails = $model->parental;
        $modelPersonals = $model->personal;
        $modelPersonalHistorys = $model->personalHistory;
        $modelQuirurgicalInterventions = $model->quirurgicalIntervention;
        $modelHospitalizations = $model->hospitalization;
        $modelGynecoObstetrics = $model->gynecoObstetric;
        $modelDiets = $model->diet;
        $modelAddictions = $model->addiction;
        $modelSystems = $model->system;
        $modelPhysicals = $model->physical;
        $modelLabtests = $model->labtest;

        $formDetails = Yii::$app->request->post('Parental', []);
        $formPersonals = Yii::$app->request->post('Personal', []);
        $formPersonalHistorys = Yii::$app->request->post('PersonalHistory', []);
        $formQuirurgicalInterventions = Yii::$app->request->post('QuirurgicalIntervention', []);
        $formHospitalizations = Yii::$app->request->post('Hospitalization', []);
        $formGynecoObstetrics = Yii::$app->request->post('GynecoObstetric', []);
        $formDiets = Yii::$app->request->post('Diet', []);
        $formAddictions = Yii::$app->request->post('Addiction', []);
        $formSystems = Yii::$app->request->post('System', []);
        $formPhysicals = Yii::$app->request->post('Physical', []);
        $formLabtests = Yii::$app->request->post('Labtest', []);


        foreach ($formGynecoObstetrics as $i => $formGynecoObstetric) {
            if (isset($formGynecoObstetric['id']) && isset($formGynecoObstetric['updateTypeGynecoObstetric']) && $formGynecoObstetric['updateTypeGynecoObstetric'] != GynecoObstetric::UPDATE_TYPE_GYNECO_OBSTETRIC_CREATE) {
                $modelGynecoObstetric = GynecoObstetric::findOne(['id' => $formGynecoObstetric['id'], 'patient_id' => $model->id]);
                $modelGynecoObstetric->setScenario(GynecoObstetric::SCENARIO_GYNECO_OBSTETRIC_BATCH_UPDATE);
                $modelGynecoObstetric->setAttributes($formGynecoObstetric);
                $modelGynecoObstetrics[$i] = $modelGynecoObstetric;
            } else {
                $modelGynecoObstetric = new GynecoObstetric(['scenario' => GynecoObstetric::SCENARIO_GYNECO_OBSTETRIC_BATCH_UPDATE]);
                $modelGynecoObstetric->setAttributes($formGynecoObstetric);
                $modelGynecoObstetrics[] = $modelGynecoObstetric;
            }
        }


        foreach ($formDiets as $i => $formDiet) {
            if (isset($formDiet['id']) && isset($formDiet['updateTypeDiet']) && $formDiet['updateTypeDiet'] != Diet::UPDATE_TYPE_DIET_CREATE) {
                $modelDiet = Diet::findOne(['id' => $formDiet['id'], 'patient_id' => $model->id]);
                $modelDiet->setScenario(Diet::SCENARIO_DIET_BATCH_UPDATE);
                $modelDiet->setAttributes($formDiet);
                $modelDiets[$i] = $modelDiet;
            } else {
                $modelDiet = new Diet(['scenario' => Diet::SCENARIO_DIET_BATCH_UPDATE]);
                $modelDiet->setAttributes($formDiet);
                $modelDiets[] = $modelDiet;
            }
        }

        foreach ($formAddictions as $i => $formAddiction) {
            if (isset($formAddiction['id']) && isset($formAddiction['updateTypeAddiction']) && $formAddiction['updateTypeAddiction'] != Addiction::UPDATE_TYPE_ADDICTION_CREATE) {
                $modelAddiction = Addiction::findOne(['id' => $formAddiction['id'], 'patient_id' => $model->id]);
                $modelAddiction->setScenario(Addiction::SCENARIO_ADDICTION_BATCH_UPDATE);
                $modelAddiction->setAttributes($formAddiction);
                $modelAddictions[$i] = $modelAddiction;
            } else {
                $modelAddiction = new Addiction(['scenario' => Addiction::SCENARIO_ADDICTION_BATCH_UPDATE]);
                $modelAddiction->setAttributes($formAddiction);
                $modelAddictions[] = $modelAddiction;
            }
        }

        if (Yii::$app->request->post('addRowGynecoObstetricAlone') == 'true') {
            $modelGynecoObstetrics[] = new GynecoObstetric(['scenario' => GynecoObstetric::SCENARIO_GYNECO_OBSTETRIC_BATCH_UPDATE]);
            return $this->render('update_gynecoobstetric', [
              'model' => $model,
              'modelPersonals' => $modelPersonals,
              'modelDetails' => $modelDetails,
              'modelPersonalHistorys' => $modelPersonalHistorys,
              'modelQuirurgicalInterventions' => $modelQuirurgicalInterventions,
              'modelHospitalizations' => $modelHospitalizations,
              'modelGynecoObstetrics' => $modelGynecoObstetrics,
              'modelDiets' => $modelDiets,
              'modelAddictions' => $modelAddictions,
              'modelSystems' => $modelSystems,
              'modelPhysicals' => $modelPhysicals,
              'modelLabtests' => $modelLabtests,
          ]);
        }


        if (Yii::$app->request->post('addRowDietAlone') == 'true') {
            $modelDiets[] = new Diet(['scenario' => Diet::SCENARIO_DIET_BATCH_UPDATE]);
            return $this->render('update_habits', [
                        'model' => $model,
                        'modelPersonals' => $modelPersonals,
                        'modelDetails' => $modelDetails,
                        'modelPersonalHistorys' => $modelPersonalHistorys,
                        'modelQuirurgicalInterventions' => $modelQuirurgicalInterventions,
                        'modelHospitalizations' => $modelHospitalizations,
                        'modelGynecoObstetrics' => $modelGynecoObstetrics,
                        'modelDiets' => $modelDiets,
                        'modelAddictions' => $modelAddictions,
                        'modelSystems' => $modelSystems,
                        'modelPhysicals' => $modelPhysicals,
                        'modelLabtests' => $modelLabtests,
                    ]);
        }

        if (Yii::$app->request->post('addRowAddictionAlone') == 'true') {
            $modelAddictions[] = new Addiction(['scenario' => Addiction::SCENARIO_ADDICTION_BATCH_UPDATE]);
            return $this->render('update_habits', [
                        'model' => $model,
                        'modelPersonals' => $modelPersonals,
                        'modelDetails' => $modelDetails,
                        'modelPersonalHistorys' => $modelPersonalHistorys,
                        'modelQuirurgicalInterventions' => $modelQuirurgicalInterventions,
                        'modelHospitalizations' => $modelHospitalizations,
                        'modelGynecoObstetrics' => $modelGynecoObstetrics,
                        'modelDiets' => $modelDiets,
                        'modelAddictions' => $modelAddictions,
                        'modelSystems' => $modelSystems,
                        'modelPhysicals' => $modelPhysicals,
                        'modelLabtests' => $modelLabtests,
                    ]);
        }

        if (Yii::$app->request->post('addRowHabits') == 'true') {
            $modelDiets[] = new Diet(['scenario' => Diet::SCENARIO_DIET_BATCH_UPDATE]);
            $modelAddictions[] = new Addiction(['scenario' => Addiction::SCENARIO_ADDICTION_BATCH_UPDATE]);
            return $this->render('update_habits', [
                        'model' => $model,
                        'modelPersonals' => $modelPersonals,

views/patient/_modify_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Cie10;
use kartik\typeahead\TypeaheadBasic;
use kartik\typeahead\Typeahead;
use kartik\switchinput\SwitchInput;
// use dosamigos\datepicker\DatePicker;
use kartik\date\DatePicker;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\db\Expression;

?>

<div class="patient-form">

    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false,
        // 'enableAjaxValidation' => true,
        'options' => ['enctype'=> 'multipart/form-data']
      ]); ?>

<div id="patient-form">

    <div class="col-md-5">
      <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'sex')->widget(SwitchInput::classname(), [
              'pluginOptions' => [
                            'onText' => '<i class="fa fa-mars"></i> Hombre',
                            'offText' => '<i class="fa fa-venus"></i> Mujer',
                            // 'handleWidth'=> 120,
                            'onValue' => false,
                            'offValue' => true,
                            'onColor' => 'primary',
                            'offColor' => 'btn btn-sample',
                      ],
                      'pluginEvents' => [
                             'switchChange.bootstrapSwitch' => 'function(event, state) {
                                 if (state == 0 || state == false  || state == null){
                                     $("#'.Html::getInputId($model, 'sex').'").attr("value", 0);

                                 }
                                 else {
                                   $("#'.Html::getInputId($model, 'sex').'").attr("value", 1);
                                 }
                             }',
                      ],
                ]);?>
    </div>

    <div class="col-md-2">
      <b>Fecha de Nacimiento </b>
      <?= DatePicker::widget([
      'attribute' => 'birth_date',
      'model' => $model,
      // 'value' => '08-Apr-2004 10:20 AM',
      'type' => DatePicker::TYPE_INPUT,
      'options' => [
        // 'placeholder' => 'Fecha de Nacimiento'
       ],
      'pluginOptions' => [
          'format' => 'yyyy-mm-dd',
          'showMeridian' => false,
          'autoclose' => true,
          'todayBtn' => false
          ]
      ]);?>
    </div>

    <?php
    $birth_year = $model->birth_date;
    $birth_year = substr($birth_year,0,4);
    $now_year = new Expression('NOW()');
              $now_year = (new \yii\db\Query)->select($now_year)->scalar();
              $now_year =substr($now_year, 0, 4);
    $birth_month = $model->birth_date;
    $birth_month = substr($birth_month,5,2);
    $now_month = new Expression('NOW()');
              $now_month = (new \yii\db\Query)->select($now_month)->scalar();
              $now_month =substr($now_month, 5, 2);
    $month_dif= $now_month-$birth_month;
    if ($birth_year == null)
    {

      $year_dif= 0;
    }
    else{
      $year_dif= $now_year-$birth_year;
    }

    if ($month_dif >= 0 ){}
      else{
      $year_dif = $year_dif - 1;
    }
    ?>


    <div class="col-md-1">
      <?= $form->field($model, 'age')->textInput(['readOnly'=>true, 'value' => $year_dif]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-md-5">
    <?= $form->field($model, 'photofile')->fileInput() ?>
  </div>
    <div class="col-md-2">
      <?= $form->field($model, 'scholarity')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'work_area')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'profession')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-1">
      <?= $form->field($model, 'experience')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'birth_place')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-3">
      <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'postal_code')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-4">
      <?= $form->field($model, 'on_emergency')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-md-2">
      <?= $form->field($model, 'emergency_phone')->textInput(['maxlength' => true]) ?>
    </div>
</div>


    <div class="form-group col-md-12">
      <?= Html::submitButton($model->isNewRecord ? '<i class="glyphicon glyphicon-floppy-disk"></i> Guardar' : '<i class="glyphicon glyphicon-floppy-disk"></i> Actualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
  </div>

views/patient/_view.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Patient;
?>

<div class="patient-view">
<div>
    <?= DetailView::widget([
        'model' => $model,
        "options" => ['class' => 'bg-gray-light table-responsive table-condensed thead-inverse table-hover table table-striped table-bordered  container-fluid', ],
        'attributes' => [
            'sex',
            'birth_date',
            'birth_place',
            'age',
            'status',
            'scholarity',
            'work_area',
            'profession',
            'experience',
            'address',
            'city',
            'postal_code',// 'phone',    'created_date',
        ],
    ]) ?>
  
  </div>
</div>

views/patient/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Patient;
use yii\widgets\ActiveForm;
use yii\db\Expression;
use yii\helpers\Url;
use yii\helpers\FileHelper;


$this->title = $model->name;
// $this->params['breadcrumbs'][] = ['label' => 'Patients', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div>
  <?= Html::a('<i class="fa fa-chevron-left"></i>', ['patient/index', 'patname' => $model->name, 'patid' => $model->id], ['class' => 'btn btn-success', 'data' => [ ],]) ?>
</div>

<div class="patient-view">
<div class="com-md-12">
    <div class="pull-right">

  <?= Html::a('<i class="fa fa-eyedropper"></i> Recetar', ['prescription/create', 'patname' => $model->name, 'patid' => $model->id], ['class' => 'btn btn-info', 'data' => [
                //  'confirm' => "Recetar?",
            ],
]) ?>
  &nbsp;
      <?= Html::a('<i class="fa fa-pencil"></i> Modificar Datos Personales', ['modify', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        &nbsp;

      <?= Html::a('<i class="fa fa-remove"></i> Eliminar', ['delete', 'id' => $model->id], [
        'class' => 'btn btn-danger',
        'data' => [
          'confirm' => 'Borrar éste Paciente?',
          'method' => 'post',
        ],
        ]) ?>

      </div>

    <div class="pull left">
        <h3><?= Html::encode($this->title) ?></h3>
    </div>
  </div>

<div>
  <?php
  $birth_year = $model->birth_date;
  $birth_year = substr($birth_year,0,4);
  $now_year = new Expression('NOW()');
            $now_year = (new \yii\db\Query)->select($now_year)->scalar();
            $just_now = substr($now_year, 0, 10);
            $now_year = substr($now_year, 0, 4);
  $birth_month = $model->birth_date;
  $birth_month = substr($birth_month,5,2);
  $now_month = new Expression('NOW()');
            $now_month = (new \yii\db\Query)->select($now_month)->scalar();
            $now_month =substr($now_month, 5, 2);
  $month_dif= $now_month-$birth_month;
  if ($birth_year == null)
  {

    $year_dif= 0;
  }
  else{
    $year_dif= $now_year-$birth_year;
  }

  if ($month_dif >= 0 ){}
    else{
    $year_dif = $year_dif - 1;
  }
  ?>

<?php if ($model->sex==0){
  $model->sex = "Mujer";
}
else{
  $model->sex = "Hombre";
}?>

<?php $model->age =  $year_dif;?>
    <?= DetailView::widget([
        'model' => $model,
        "options" => ['class' => 'bg-gray-light   table table-striped ', ],
        'attributes' => [
            // 'id',
              ['attribute'=>'photo',
              'label'=> 'Fotografía',
              'value'=> $model->photo,
              'format'=>['image',['width'=>100, 'height'=>100]]
            ],
            'on_emergency',            'emergency_phone',
            // 'modified_date',            // 'name',
            'sex',            'birth_date',            'birth_place',            'age',            'status',
            'scholarity',            'work_area',            'profession',            'experience',            'address',
            'city',            'postal_code',            'phone',            'created_date',
        ],
    ]) ?>
  </div>


  <?php if (($model->parental || $model->personal || $model->quirurgicalIntervention || $model->hospitalization || $model->personalHistory || $model->system) == null) {
    } else {
        echo "<hr>&nbsp;<div>
      <h3>Historia Clínica</h3>
      </div>&nbsp;";
    }?>


    <?php echo Yii::$app->controller->renderPartial('partials/parentals', ["model"=>$model], true); ?>

    <?php echo Yii::$app->controller->renderPartial('partials/personals', ["model"=>$model], true); ?>

    <?php echo Yii::$app->controller->renderPartial('partials/quirurgicals', ["model"=>$model], true); ?>

    <?php echo Yii::$app->controller->renderPartial('partials/hospitalizations', ["model"=>$model], true); ?>

    <?php echo Yii::$app->controller->renderPartial('partials/personalhistorys', ["model"=>$model], true); ?>

    <?php echo Yii::$app->controller->renderPartial('partials/systems', ["model"=>$model], true); ?>



    <div class="pull-right">
        <?php
        echo "<p>";
        echo Html::a('<i class="fa fa-pencil"></i> Actualizar Historia Clínica', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']);
        echo "</p>"?>
    </div>


    <?php echo Yii::$app->controller->renderPartial('partials/gynecoobstetrics', ["model"=>$model], true); ?>


        <?php ActiveForm::begin(); ?>

        <div class="pull-left">
          <?php if ($model->gynecoObstetric == true) {
    } else {
        if ($model->sex ==0 || $model->sex == null) {
            echo Html::submitButton('<i class="fa fa-pencil"></i> Agregar Datos Gineco-Obstétricos', ['name' => 'addRowGynecoObstetricAlone', 'value' => 'true', 'class' => 'btn addRowGynecoObstetricAlone btn-sample']);
        }
    }
          ?>
        </div>
        <?php ActiveForm::end(); ?>

        <div class="pull-left">
          <?php
          if ($model->gynecoObstetric == true) {
              if ($model->sex == 0 || $model->sex == null) {
                  echo Html::a('<i class="fa fa-pencil"></i> Datos Gineco-Obstétricos', ['addgynecoobstetric', 'id' => $model->id], ['class' => 'btn btn-sample']);
              } else {
              }
          }
          ?>
        </div>
<div>




              <?php echo Yii::$app->controller->renderPartial('partials/allergies', ["model"=>$model], true); ?>


              <div class="pull-left">
                 <?php foreach ($model->system as $system) :?>
                <?php if ($model->system !== true) {
                    if (($system->allergy == false) || ($system->allergy == null)) {
                    } else {
                        echo Html::a('<i class="fa fa-pencil"></i> Alérgias', ['addallergics', 'id' => $model->id], ['class' => 'btn btn-warning']);
                    }
                }
                ?>
              <?php endforeach;?>
              </div>

              <?php echo Yii::$app->controller->renderPartial('partials/habits', ["model"=>$model], true); ?>

        <?php ActiveForm::begin(); ?>
        <?php
        if ($model->diet == true) {
        } else {
            if ($model->addiction == false) {


                echo "<p>";
                // echo Html::a('<i class="fa fa-pencil"></i> Agregar Hábitos', ['addhabits', 'id' => $model->id], ['class' => 'addRowHabits btn btn-warning']);

                echo Html::submitButton('<i class="fa fa-pencil"></i> Agregar Hábitos', ['name' => 'addRowHabits', 'value' => 'true', 'class' => 'btn addRowHabits btn-success']);
                echo "</p>";
            }
        }
        ?>
        <?php if ($model->diet == true) {
        } else {
            if ($model->addiction == true) {
                echo "<p>";
                echo Html::submitButton('<i class="fa fa-pencil"></i> Agregar Hábitos Dietéticos', ['name' => 'addRowDietAlone', 'value' => 'true', 'class' => 'btn addRowDietAlone btn-warning']);
                echo "</p>";
            }
        }?>

        <?php if ($model->addiction == true) {
        } else {
            if ($model->diet == true) {
                echo "<p>";
                echo Html::submitButton('<i class="fa fa-pencil"></i> Agregar Otros Hábitos', ['name' => 'addRowAddictionAlone', 'value' => 'true', 'class' => 'btn addRowAddictionAlone btn-info']);
                echo "</p>";
            }
        }?>
        <?php ActiveForm::end(); ?>

        <?php if (($model->diet == true) && ($model->addiction == true)) {
            echo "<p>";
            echo Html::a('<i class="fa fa-pencil"></i> Hábitos', ['addhabits', 'id' => $model->id], ['class' => 'btn btn-info']);
            echo "</p>";
        } else {
        }
        ?>
        <?php echo Yii::$app->controller->renderPartial('partials/physicals', ["model"=>$model], true); ?>


                <div class="pull-right">
                    <?= Html::a('<i class="fa fa-thermometer-3"></i> Agregar Exámen Físico', ['addphysical', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                </div>

        <?php echo Yii::$app->controller->renderPartial('partials/analysis', ["model"=>$model], true); ?>




    <div class="pull-left">
        <?= Html::a('<i class="fa fa-tint"></i> Agregar Análisis Clínico', ['addanalysis', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </div>

    <?php echo Yii::$app->controller->renderPartial('partials/attachments', ["model"=>$model], true); ?>


      <div class="col-md-12">

        <div class="pull-right">
          <?= Html::a('<i class="fa fa-paperclip"></i> Anexos', ['patient/upload', 'id' => $model->id], ['class' => 'btn btn-warning', 'data' => [ ],]) ?>
        </div>
      </div>
</div>