models/Prescription.php
<?php
namespace app\models;

use Yii;

class Prescription extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'prescription';
    }
    public function rules()
    {
        return [
          [['patient','doctor',
          // 'diagnosis','cie10_code'
        ], 'required'],
            // ['date', 'required'],
            [['patient', 'doctor',
            // 'diagnosis', 'cie10_code',
             'date', 'valid_until' ,'note'], 'string', 'max' => 255],
        ];
    }
    public function attributeLabels()
    {
        return [
            'id' => 'Fólio',
            // 'cie10_code' => 'CIE10',
            'patient' => 'Paciente',
            'doctor' => 'Médico',
            // 'diagnosis' => 'Diagnóstico',
            'date' => 'Fecha',
            'valid_until' => 'Caducidad',
            'note' => 'Anotaciones',
        ];
    }

    public function getPrescriptionDetails()
    {
        return $this->hasMany(PrescriptionDetail::className(), ['prescription_id' => 'id']);
    }


    public function getPrescriptionDiagnostics()
    {
        return $this->hasMany(PrescriptionDiagnostic::className(), ['prescription_id' => 'id']);
    }

    public function getCie10()
    {
        return $this->hasOne(Cie10::className(), ['id10' => 'cie10_code']);
    }
}

controllers/PrescriptionController.php
<?php
namespace app\controllers;

use app\models\PrescriptionDetail;
use app\models\PrescriptionDiagnostic;
use Yii;
use app\models\Prescription;
use app\models\PrescriptionSearch;
use app\models\Cie10;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
// use kartik\mpdf\Pdf;
use mPDF;

class PrescriptionController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new PrescriptionSearch();
        // $dataProvider = new ActiveDataProvider([
        //     'query' => Prescription::find(),
        // ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new Prescription();
        $modelDetails = [];
        $modelDiagnostics = [];

        $formDetails = Yii::$app->request->post('PrescriptionDetail', []);
        foreach ($formDetails as $i => $formDetail) {
            $modelDetail = new PrescriptionDetail(['scenario' => PrescriptionDetail::SCENARIO_BATCH_UPDATE]);
            $modelDetail->setAttributes($formDetail);
            $modelDetails[] = $modelDetail;
        }

        $formDiagnostics = Yii::$app->request->post('PrescriptionDiagnostic', []);
        foreach ($formDiagnostics as $i => $formDiagnostic) {
            $modelDiagnostic = new PrescriptionDiagnostic(['scenario' => PrescriptionDiagnostic::SCENARIO_DIAGNOSTIC_BATCH_UPDATE]);
            $modelDiagnostic->setAttributes($formDiagnostic);
            $modelDiagnostics[] = $modelDiagnostic;
        }

        //handling if the addRow button has been pressed
        if (Yii::$app->request->post('addRow') == 'true') {
            $model->load(Yii::$app->request->post());
            $modelDetails[] = new PrescriptionDetail(['scenario' => PrescriptionDetail::SCENARIO_BATCH_UPDATE]);
            return $this->render('create', [
                'model' => $model,
                'modelDetails' => $modelDetails,
                'modelDiagnostics' => $modelDiagnostics
            ]);
        }

        if (Yii::$app->request->post('addRowDiagnostic') == 'true') {
            $model->load(Yii::$app->request->post());
            $modelDiagnostics[] = new PrescriptionDiagnostic(['scenario' => PrescriptionDiagnostic::SCENARIO_DIAGNOSTIC_BATCH_UPDATE]);
            return $this->render('create', [
                'model' => $model,
                'modelDetails' => $modelDetails,
                'modelDiagnostics' => $modelDiagnostics

            ]);
        }

        if ($model->load(Yii::$app->request->post())) {
            if (Model::validateMultiple($modelDetails) || ($modelDiagnostics) && $model->validate()) {
                $model->save();
                foreach ($modelDetails as $modelDetail) {
                    $modelDetail->prescription_id = $model->id;
                    $modelDetail->save();
                }
                foreach ($modelDiagnostics as $modelDiagnostic) {
                    $modelDiagnostic->prescription_id = $model->id;
                    $modelDiagnostic->save();
                }

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'modelDetails' => $modelDetails,
            'modelDiagnostics' => $modelDiagnostics
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelDetails = $model->prescriptionDetails;
        $modelDiagnostics = $model->prescriptionDiagnostics;


        $formDetails = Yii::$app->request->post('PrescriptionDetail', []);
        $formDiagnostics = Yii::$app->request->post('PrescriptionDiagnostic', []);

        foreach ($formDetails as $i => $formDetail) {
            //loading the models if they are not new
            if (isset($formDetail['id']) && isset($formDetail['updateType']) && $formDetail['updateType'] != PrescriptionDetail::UPDATE_TYPE_CREATE) {
                //making sure that it is actually a child of the main model
                $modelDetail = PrescriptionDetail::findOne(['id' => $formDetail['id'], 'prescription_id' => $model->id]);
                $modelDetail->setScenario(PrescriptionDetail::SCENARIO_BATCH_UPDATE);
                $modelDetail->setAttributes($formDetail);
                $modelDetails[$i] = $modelDetail;
                //validate here if the modelDetail loaded is valid, and if it can be updated or deleted
            } else {
                $modelDetail = new PrescriptionDetail(['scenario' => PrescriptionDetail::SCENARIO_BATCH_UPDATE]);
                $modelDetail->setAttributes($formDetail);
                $modelDetails[] = $modelDetail;
            }
        }

        foreach ($formDiagnostics as $i => $formDiagnostic) {
            //loading the models if they are not new
            if (isset($formDiagnostic['id']) && isset($formDiagnostic['updateTypeDiagnostic']) && $formDiagnostic['updateTypeDiagnostic'] != PrescriptionDiagnostic::UPDATE_TYPE_DIAGNOSTIC_CREATE) {
                //making sure that it is actually a child of the main model
                $modelDiagnostic = PrescriptionDiagnostic::findOne(['id' => $formDiagnostic['id'], 'prescription_id' => $model->id]);
                $modelDiagnostic->setScenario(PrescriptionDiagnostic::SCENARIO_DIAGNOSTIC_BATCH_UPDATE);
                $modelDiagnostic->setAttributes($formDiagnostic);
                $modelDiagnostics[$i] = $modelDiagnostic;
                //validate here if the modelDiagnostic loaded is valid, and if it can be updated or deleted
            } else {
                $modelDiagnostic = new PrescriptionDiagnostic(['scenario' => PrescriptionDiagnostic::SCENARIO_DIAGNOSTIC_BATCH_UPDATE]);
                $modelDiagnostic->setAttributes($formDiagnostic);
                $modelDiagnostics[] = $modelDiagnostic;
            }
        }
        //handling if the addRow button has been pressed
        if (Yii::$app->request->post('addRow') == 'true') {
            $modelDetails[] = new PrescriptionDetail(['scenario' => PrescriptionDetail::SCENARIO_BATCH_UPDATE]);
            return $this->render('update', [
                'model' => $model,
                'modelDetails' => $modelDetails,
                'modelDiagnostics' => $modelDiagnostics

            ]);
        }

        if (Yii::$app->request->post('addRowDiagnostic') == 'true') {
            $modelDiagnostics[] = new PrescriptionDiagnostic(['scenario' => PrescriptionDiagnostic::SCENARIO_DIAGNOSTIC_BATCH_UPDATE]);
            return $this->render('update', [
                'model' => $model,
                'modelDetails' => $modelDetails,
                'modelDiagnostics' => $modelDiagnostics

            ]);
        }
        if ($model->load(Yii::$app->request->post())) {
            if (Model::validateMultiple($modelDetails) || ($modelDiagnostics) && $model->validate()) {
                $model->save();
                foreach ($modelDetails as $modelDetail) {
                    //details that has been flagged for deletion will be deleted
                    if ($modelDetail->updateType == PrescriptionDetail::UPDATE_TYPE_DELETE) {
                        $modelDetail->delete();
                    } else {
                        //new or updated records go here
                        $modelDetail->prescription_id = $model->id;
                        $modelDetail->save();
                    }
                }


                foreach ($modelDiagnostics as $modelDiagnostic) {
                    //details that has been flagged for deletion will be deleted
                    if ($modelDiagnostic->updateTypeDiagnostic == PrescriptionDiagnostic::UPDATE_TYPE_DIAGNOSTIC_DELETE) {
                        $modelDiagnostic->delete();
                    } else {
                        //new or updated records go here
                        $modelDiagnostic->prescription_id = $model->id;
                        $modelDiagnostic->save();
                    }
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('update', [
            'model' => $model,
            'modelDetails' => $modelDetails,
            'modelDiagnostics' => $modelDiagnostics
        ]);
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        foreach ($model->prescriptionDetails as $modelDetail) {
            $modelDetail->delete();
        }
        foreach ($model->prescriptionDiagnostics as $modelDiagnostic) {
            $modelDiagnostic->delete();
        }
        $model->delete();
        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Prescription::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPdf($id)
    {
        $model = $this->findModel($id);
        $mpdf = new mPDF('', 'letter', 9, 'dejavusans');
        $mpdf->SetDefaultBodyCSS('color', '#000000');
        $mpdf->AddPage('portrait');
        $mpdf->useDefaultCSS2 = true;
        $mpdf->SetTitle($model->patient);

        $mpdf->WriteHTML('
        <div style="margin-bottom:20px;">
        <table width="100%">

views/prescription/_form.php
<?php
use app\models\Patient;
use app\models\Doctor;
use app\models\Cie10;
use app\models\Prescription;
use app\models\PrescriptionDetail;
use app\models\PrescriptionDiagnostic;
use app\models\Allergic;

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\typeahead\TypeaheadBasic;
use kartik\typeahead\Typeahead;
use dosamigos\datepicker\DatePicker;
use dosamigos\datepicker\DateRangePicker;
use yii\db\Query;
use app\models\Drug;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;
// use kartik\grid\GridView;
use yii\grid\GridView;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;

?>
<?php $this->registerJs("
    $('.delete-button').click(function() {
        var detail = $(this).closest('.prescription-detail');
        var updateType = detail.find('.update-type');
        if (updateType.val() === " . json_encode(PrescriptionDetail::UPDATE_TYPE_UPDATE) . ") {
            updateType.val(" . json_encode(PrescriptionDetail::UPDATE_TYPE_DELETE) . ");
            detail.hide();
        } else {
            detail.remove();
        }

    });

    $('.delete-button-diagnostic').click(function() {
        var diagnostic = $(this).closest('.prescription-diagnostic');
        var updateTypeDiagnostic = diagnostic.find('.update-type-diagnostic');
        if (updateTypeDiagnostic.val() === " . json_encode(PrescriptionDiagnostic::UPDATE_TYPE_DIAGNOSTIC_UPDATE) . ") {
            updateTypeDiagnostic.val(" . json_encode(PrescriptionDiagnostic::UPDATE_TYPE_DIAGNOSTIC_DELETE) . ");
            diagnostic.hide();
        } else {
            diagnostic.remove();
        }

    });

");
?>

<div class="prescription-form">

    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false
    ]); ?>

    <?php
      $patname = Yii::$app->getRequest()->getQueryParam('patname');
      // echo $patname;
      $patid = Yii::$app->getRequest()->getQueryParam('patid');
      // echo $patid;
    ?>

    <?php $pmod = $model->patient;
        $pat = Patient::find()->where(['name'=>$pmod])->one();
        $pid = $pat['id'];
        if (($patid == null)||($patid == false)) {
            $allergicProvider = new ActiveDataProvider([
            'query' => Allergic::find()->where(['patient_id'=> $pid]),
            'sort' => false
          ]);
        } else {
            $allergicProvider = new ActiveDataProvider([
              'query' => Allergic::find()->where(['patient_id'=> $patid]),
              'sort' => false
            ]
          );
        }
    ?>

    <?php
    $patientData = ArrayHelper::map(Patient::find()->all(), 'id', 'name')
    ?>
        <div class="col-md-6">
            <?php
            if (($patname == null)||($patname == false)) {
                echo $form->field($model, 'patient')->label('Paciente')->widget(TypeaheadBasic::classname(), [
                'data' => $patientData,
                'scrollable' => true,
                'options' => [  'placeholder' => 'Paciente'],
                'pluginOptions' => ['highlight'=>true],
              ]);
            } else {
                echo $form->field($model, 'patient')->label('Paciente')->widget(TypeaheadBasic::classname(), [
              'data' => $patientData,
              'scrollable' => true,
              'options' => [ 'readOnly' => true, 'placeholder' => 'Paciente', 'value' => $patname],
              'pluginOptions' => ['highlight'=>true],
            ]);
            }
            ?>
        </div>

        <?php
        $doctorData = ArrayHelper::map(Doctor::find()->all(), 'id', 'name')
        ?>
        <div class="col-md-6">
            <?= $form->field($model, 'doctor')->label('Médico')->widget(TypeaheadBasic::classname(), [
              'data' => $doctorData,
              'scrollable' => true,
              'options' => ['placeholder' => 'Médico'],
              'pluginOptions' => ['highlight'=>true],
            ]);
            ?>
        </div>


        <?php
        $cie10Data = ArrayHelper::map(Cie10::find()->all(), 'id10', 'dec10');
        ?>

<!--
<div class="col-md-3">

  <?= $form->field($model, 'date')->label('Fecha')->widget(DatePicker::className(), [
      'attribute' => 'date',
      'model'=>$model,
          'template' => '{addon}{input}',
      // 'form' => $form, // best for correct client validation
      'language' => 'es',

      'clientOptions' => [
          'autoclose' => true,
          'format' => 'dd-M-yyyy'
      ]
  ]);?>
  </div> -->

  <div class="col-md-3">
      <?= $form->field($model, 'valid_until')->label('Caducidad')->widget(DatePicker::className(), [
          'attribute' => 'valid_until',
          'model'=>$model,
              'template' => '{addon}{input}',
          // 'form' => $form, // best for correct client validation
          'language' => 'es',

          'clientOptions' => [
              'autoclose' => true,
              'format' => 'yyyy-mm-dd'
          ]
      ]);?>
  </div>

  <div class="col-md-9">
    <?= $form->field($model, 'note')->label('Anotaciones')->textInput(['maxlength' => true]) ?>
  </div>


  <div class="col-md-9">
    <?php
    $count = $allergicProvider->getCount();
    if ($count !== 0) {
        echo yii\grid\GridView::widget([
        'dataProvider' => $allergicProvider,
        'layout' => "{pager}\n{items}",
        'columns'=> [['attribute' => 'allergy', 'label' => 'Alérgia(s)']],
      ]);
    } else {
    }
    ?>
  </div>


  <?php Pjax::begin(); ?>

  <?php foreach ($modelDiagnostics as $i => $modelDiagnostic) : ?>
      <div class="row prescription-diagnostic prescription-diagnostic-<?= $i ?>">
          <div class="col-md-12">
              <?= Html::activeHiddenInput($modelDiagnostic, "[$i]id") ?>
              <?= Html::activeHiddenInput($modelDiagnostic, "[$i]updateTypeDiagnostic", ['class' => 'update-type-diagnostic']) ?>
              <table>
                  <tr class="col-md-14">
                    <td class="col-md-12">
                        <?=  $form->field($modelDiagnostic, "[$i]diagnostic")->label('Diagnóstico')->widget(TypeaheadBasic::classname(), [
                          'data'=>$cie10Data,
                          'scrollable' => true,
                          // 'attribute'=>'diagnosis',
                          'options' => ['placeholder' => 'Diagnóstico'],
                          'pluginOptions' => ['highlight'=>true],
                          'pluginEvents' => [
                                        'typeahead:selected' => 'function(){

                                          log("typeahead:closed");
                                          }',
                                        ],
                          ])?>
                      </td>
                      <td class="col-md-1">
                          <?= Html::button('x', ['class' => 'delete-button-diagnostic btn btn-danger', 'data-target' => "prescription-diagnostic-$i"]) ?>
                      </td>
                    </tr>

                          <?php $code = Cie10::find()->select('id10')->where(['dec10' => $modelDiagnostic->diagnostic])->one(); ?>
                          <?php if (isset($code->id10) == true){
                            $nicecode = $code->id10;
                          }
                          else{$nicecode = 'nocode';}
                          ?>
                  <tr class="col-md-14" style="display:none">
                    <td class="col-md-14" style="display:none">
                          <?= $form->field($modelDiagnostic, "[$i]cie10_code")->textInput(['maxlength' => true, 'value' => $nicecode ]) ?>
                    </td>
                  </tr>

              </table>

          </div>
      </div>
  <?php endforeach; ?>

    <?php foreach ($modelDetails as $i => $modelDetail) : ?>
      <hr>
        <div class="row prescription-detail prescription-detail-<?= $i ?>">
            <div class="col-md-14">
                <?= Html::activeHiddenInput($modelDetail, "[$i]id") ?>
                <?= Html::activeHiddenInput($modelDetail, "[$i]updateType", ['class' => 'update-type']) ?>
                <?php
                $drugData = ArrayHelper::map(Drug::find()->all(), 'id', 'nombre')
                ?>
                <table>

                    <tr class="col-md-12">
                      <td class="col-md-2">
                        <?= $form->field($modelDetail, "[$i]quantity")->label('Cantidad')->textInput(['maxlength' => 255]) ?>
                      </td>
                      <td class="col-md-10">
                        <?= $form->field($modelDetail, "[$i]medicine_name")->label('Medicamento')->widget(TypeaheadBasic::classname(), [
                          'data' => $drugData,
                          'scrollable' => true,
                          'options' => ['placeholder' => 'Medicamento'],
                          'pluginOptions' => ['highlight'=>true],
                        ]);
                        ?>
                      </td>
                    </tr>
                    <tr class="col-md-12">
                      <td class="col-md-2">
                        <?= $form->field($modelDetail, "[$i]dosage")->label('Tomar')->textInput(['maxlength' => 255]) ?>
                      </td>
                      <td class="col-md-2">
                        <?= $form->field($modelDetail, "[$i]frequency")->label('Cada')->textInput(['maxlength' => 255]) ?>
                      </td>
                      <td class="col-md-2">
                        <?= $form->field($modelDetail, "[$i]duration")->label('Durante')->textInput(['maxlength' => 255]) ?>
                      </td>
                      <td class="col-md-6">
                        <?= $form->field($modelDetail, "[$i]indication")->label('Indicación')->textInput(['maxlength' => 255]) ?>
                      </td>
                      <td class="col-md-1">
                        <?= Html::button('x', ['class' => 'delete-button btn btn-danger', 'data-target' => "prescription-detail-$i"]) ?>
                      </td>
                    </tr>
                </table>

            </div>
        </div>
    <?php endforeach; ?>


    <?php Pjax::end(); ?>
    <div class="form-group col-md-12">
      <div class="pull-left col-md-2">
        <?= Html::submitButton('<i class="fa fa-plus"></i> Agregar Medicamento', ['name' => 'addRow', 'value' => 'true', 'class' => 'btn btn-info']) ?>
      </div>
      <div class="col-md-2">
        <?= Html::submitButton('<i class="fa fa-plus"></i> Agregar Diagnóstico', ['name' => 'addRowDiagnostic', 'value' => 'true', 'class' => 'btn btn-primary']) ?>
      </div>
      <div class="pull-right">
        <?= Html::submitButton($model->isNewRecord ? '<i class="fa fa-eyedropper"></i> Recetar' : 'Actualizar', ['class' => $model->isNewRecord ? 'btn btn-info' : 'btn btn-info']) ?>
      </div>
  </div>


    <?php ActiveForm::end(); ?>

</div>

views/prescription/_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\mpdf\Pdf;
use app\models\Prescription;
?>
<div class="prescription-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            // 'patient',
            // 'doctor',
            // 'date',
            'valid_until',
            'diagnosis',
            'cie10_code',
        ],
    ]) ?>
    <!-- <h2>Details</h2> -->
    <table class="prescription-details table">
        <tr>
            <!-- <th>ID</th> -->
            <th>Cantidad</th>
            <th>Medicamento</th>
            <th>Dósis</th>
            <th>Frecuéncia</th>
            <th>Duración</th>
            <th>Indicación</th>

        </tr>
        <?php foreach($model->prescriptionDetails as $prescriptionDetail) :?>
            <tr>
                <!-- <td><?= $prescriptionDetail->id ?></td> -->
                <td><?= $prescriptionDetail->quantity ?></td>
                <td><?= $prescriptionDetail->medicine_name ?></td>
                <td><?= $prescriptionDetail->dosage ?></td>
                <td><?= $prescriptionDetail->frequency ?></td>
                <td><?= $prescriptionDetail->duration ?></td>
                <td><?= $prescriptionDetail->indication ?></td>

            </tr>
        <?php endforeach; ?>
    </table>


</div>

views/prescription/create.php
<?php
use yii\helpers\Html;
$this->title = 'Crear Receta';
?>
<div class="form-group col-md-12">
  <?= Html::a('<i class="fa fa-chevron-left"></i>', ['prescription/index'], ['class' => 'btn btn-success', 'data' => [ ],]) ?>
</div>
<div class="prescription-create">
    <!-- <h1><?= Html::encode($this->title) ?></h1> -->
    <?= $this->render('_form', [
        'model' => $model,
        'modelDetails' => $modelDetails,
        'modelDiagnostics' => $modelDiagnostics
    ]) ?>
</div>

views/prescription/index.php
<?php

use yii\helpers\Html;
// use yii\grid\GridView;
use kartik\grid\GridView;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use app\models\Cie10;
use yii\widgets\Pjax;

$this->title = 'Recetas';
?>
<div class="prescription-index">
  <?php Pjax::begin(); ?>
    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

      <div class="col-md-12">
        <div class="pull-left">
          <p>
          <?= Html::a('<i class="fa fa-eyedropper"></i> Nueva Receta', ['prescription/create', 'patname' => null, 'patid' => null], ['class' => 'btn btn-success', 'data' => [
                          'method' => 'post',
                    ],
          ]) ?>
        </p>
        </div>
      </div>
<?php
$diagnosisData = ArrayHelper::map(Cie10::find()->orderBy('id10')->asArray()->all(), 'id10', 'dec10');
?>
<?php $gridColumns = [
    // ['class' => 'yii\grid\SerialColumn'],
    [
        'class'=>'kartik\grid\SerialColumn',
        'contentOptions'=>['class'=>'kartik-sheet-style'],
        'width'=>'36px',
        'header'=>'',
        'headerOptions'=>['class'=>'kartik-sheet-style']
    ],
    [
        'class'=>'kartik\grid\ExpandRowColumn',
        'width'=>'50px',
        'value'=>function ($model, $key, $index, $column) {
            return GridView::ROW_COLLAPSED;
        },
        'detail'=>function ($model, $key, $index, $column) {
            return Yii::$app->controller->renderPartial('_view', ['model'=>$model]);
        },
        'headerOptions'=>['class'=>'kartik-sheet-style'],
        'expandOneOnly'=>true,
        'hiddenFromExport' => false,
    ],
    // [
    //   'pageSummary'=>true,
    //     'attribute'=>'diagnosis',
    //     'vAlign' => 'middle',
    //     'hAlign' => 'center',
    //     'width' => '80px',
    //     'filterType' =>GridView::FILTER_SELECT2,
    //     'filter' => $diagnosisData,
    //     'filterWidgetOptions'=> [
    //                 'pluginOptions' => [
    //                     'allowClear' => true,
    //         ],
    //     ],
    //     'filterInputOptions'=>['placeholder'=>'Diagnóstico'],
    // ],
    // 'id',
    'diagnosis',
    'patient',
    'doctor',
    'date',

    ['class' => 'yii\grid\ActionColumn'],
]?>

    <?= GridView::widget([
      'dataProvider'=> $dataProvider,
      'filterModel' => $searchModel,
      'columns' => $gridColumns,
      'headerRowOptions'=>['class'=>'kartik-sheet-style'],
      'filterRowOptions'=>['class'=>'kartik-sheet-style'],
      'resizableColumns'=>true,
      'pjax'=>true,
      'bordered'=>true,
      'striped'=>true,
      'condensed'=>true,
      'showPageSummary'=>false,
      'panel'=>[
          'type'=>GridView::TYPE_PRIMARY,
          'heading'=>false,
          ],
      'persistResize'=>true,
      'pjaxSettings'=>[
          'neverTimeout'=>true,
            ],
      'responsive'=>true,
      'hover'=>true,
      'toolbar'=> [
            '{export}',
            '{toggleData}',
            ],
      'export'=>[
            // 'fontAwesome' => true,
            'PDF' => [
                    'options' => [
                        // 'title' => $tituloexport,
                        //  'subject' => $tituloexport,
                        // 'author' => 'NYCSPrep CIMS',
                        // 'keywords' => 'NYCSPrep, preceptors, pdf'
                    ]
                ],
            ],
      'exportConfig' => [
            GridView::EXCEL => [
              'label' => 'Guardar en XLS',
              'showHeader' => true,
              // 'filename' => $tituloexport,


            ],
            GridView::PDF => [
              'label' => 'Guardar en PDF',
              'showHeader' => true,
              'showCaption' => true,
              'showPageSummary' => true,
              'showFooter' => true,
              // 'title' => $tituloexport,
              // 'options' => ['title' => $tituloexport],
              // 'config' => ['options' => ['title' => $tituloexport],],
              // 'filename' => $tituloexport,
            ],
      ]

    ]); ?>
    <?php Pjax::end(); ?>
</div>

views/prescription/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Prescription */
/* @var $modelDetails app\models\PrescriptionDetail */

$this->title = 'Actualizar Receta: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Recetas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="prescription-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelDetails' => $modelDetails,
        'modelDiagnostics' => $modelDiagnostics
        
    ]) ?>

</div>